# Generated by Django 5.1 on 2025-08-23 14:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("analyst", "Security Analyst"),
                            ("viewer", "Read-Only Viewer"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True, help_text="Tenant for data isolation", null=True
                    ),
                ),
                (
                    "workspace",
                    models.CharField(
                        blank=True,
                        help_text="User workspace identifier",
                        max_length=100,
                    ),
                ),
                ("is_mfa_enabled", models.BooleanField(default=False)),
                ("failed_login_attempts", models.PositiveIntegerField(default=0)),
                ("last_failed_login", models.DateTimeField(blank=True, null=True)),
                ("is_locked_out", models.BooleanField(default=False)),
                ("lockout_until", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "auth_users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("login_failed", "Failed Login"),
                            ("logout", "User Logout"),
                            ("session_created", "Session Created"),
                            ("session_terminated", "Session Terminated"),
                            ("session_ip_changed", "Session IP Changed"),
                            ("query_generate", "Query Generation"),
                            ("query_execute", "Query Execution"),
                            ("data_export", "Data Export"),
                            ("user_create", "User Creation"),
                            ("user_modify", "User Modification"),
                            ("user_delete", "User Deletion"),
                            ("role_change", "Role Change"),
                            ("system_config", "System Configuration"),
                            ("security_event", "Security Event"),
                            ("policy_evaluated", "Policy Evaluated"),
                            ("rate_limit_exceeded", "Rate Limit Exceeded"),
                            ("suspicious_activity", "Suspicious Activity"),
                        ],
                        default="login",
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("login", "User Login"),
                            ("login_failed", "Failed Login"),
                            ("logout", "User Logout"),
                            ("session_created", "Session Created"),
                            ("session_terminated", "Session Terminated"),
                            ("session_ip_changed", "Session IP Changed"),
                            ("query_generate", "Query Generation"),
                            ("query_execute", "Query Execution"),
                            ("data_export", "Data Export"),
                            ("user_create", "User Creation"),
                            ("user_modify", "User Modification"),
                            ("user_delete", "User Deletion"),
                            ("role_change", "Role Change"),
                            ("system_config", "System Configuration"),
                            ("security_event", "Security Event"),
                            ("policy_evaluated", "Policy Evaluated"),
                            ("rate_limit_exceeded", "Rate Limit Exceeded"),
                            ("suspicious_activity", "Suspicious Activity"),
                        ],
                        default="login",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("endpoint", models.CharField(blank=True, max_length=255)),
                ("resource_type", models.CharField(blank=True, max_length=100)),
                ("resource_id", models.CharField(blank=True, max_length=100)),
                ("tenant_id", models.UUIDField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SecurityPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("login", "Login Policy"),
                            ("password", "Password Policy"),
                            ("session", "Session Policy"),
                            ("access", "Access Control Policy"),
                            ("rate_limit", "Rate Limiting Policy"),
                            ("mfa", "Multi-Factor Authentication Policy"),
                            ("ip_restriction", "IP Restriction Policy"),
                            ("time_restriction", "Time Restriction Policy"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "user_role",
                    models.CharField(
                        choices=[
                            ("all", "All Users"),
                            ("admin", "Administrator"),
                            ("analyst", "Security Analyst"),
                            ("viewer", "Read-Only Viewer"),
                        ],
                        default="all",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100, help_text="Lower numbers = higher priority"
                    ),
                ),
                (
                    "policy_config",
                    models.JSONField(help_text="Policy rules and parameters"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "security_policies",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="JWT token ID",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "session_token",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("os", models.CharField(blank=True, max_length=100)),
                ("device", models.CharField(blank=True, max_length=100)),
                (
                    "location_country",
                    models.CharField(
                        blank=True, help_text="ISO country code", max_length=2
                    ),
                ),
                ("location_city", models.CharField(blank=True, max_length=100)),
                (
                    "security_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(default=0.5, help_text="Risk score 0-1"),
                ),
                ("is_suspicious", models.BooleanField(default=False)),
                ("request_count", models.PositiveIntegerField(default=0)),
                (
                    "session_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional session metadata",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("is_terminated", models.BooleanField(default=False)),
                ("terminated_at", models.DateTimeField(blank=True, null=True)),
                ("termination_reason", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_user_sessions",
            },
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["tenant_id"], name="auth_users_tenant__d2c95b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["role"], name="auth_users_role_8a5295_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["is_active", "is_locked_out"],
                name="auth_users_is_acti_cf5063_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="audit_logs_user_id_88267f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["event_type", "timestamp"], name="audit_logs_event_t_222f56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "timestamp"], name="audit_logs_action_474804_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["severity", "timestamp"], name="audit_logs_severit_549d29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["tenant_id", "timestamp"], name="audit_logs_tenant__eb751d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitypolicy",
            index=models.Index(
                fields=["policy_type", "is_active"],
                name="security_po_policy__cc1cc0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securitypolicy",
            index=models.Index(
                fields=["user_role", "is_active"], name="security_po_user_ro_44734c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitypolicy",
            index=models.Index(
                fields=["priority"], name="security_po_priorit_fcb4eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "is_terminated"], name="auth_user_s_user_id_97a6d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["expires_at"], name="auth_user_s_expires_3df8ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["session_id"], name="auth_user_s_session_47d4a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["is_suspicious"], name="auth_user_s_is_susp_6e0b83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["security_level"], name="auth_user_s_securit_825036_idx"
            ),
        ),
    ]
