# Generated by Django 5.1 on 2025-08-23 14:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("current_value", models.FloatField()),
                ("message", models.TextField()),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "analytics_alerts",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("threshold", "Threshold Alert"),
                            ("trend", "Trend Alert"),
                            ("anomaly", "Anomaly Detection"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(
                        help_text="Name of metric to monitor", max_length=200
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("gt", "Greater Than"),
                            ("lt", "Less Than"),
                            ("eq", "Equal To"),
                            ("gte", "Greater Than or Equal"),
                            ("lte", "Less Than or Equal"),
                        ],
                        max_length=10,
                    ),
                ),
                ("threshold_value", models.FloatField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "notification_channels",
                    models.JSONField(
                        default=list, help_text="List of notification channels"
                    ),
                ),
                (
                    "cooldown_minutes",
                    models.PositiveIntegerField(
                        default=60, help_text="Cooldown period between alerts"
                    ),
                ),
                ("tenant_id", models.UUIDField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("trigger_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "analytics_alert_rules",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("total_users", models.PositiveIntegerField(default=0)),
                ("active_users_24h", models.PositiveIntegerField(default=0)),
                ("new_users_7d", models.PositiveIntegerField(default=0)),
                ("user_growth_rate", models.FloatField(default=0.0)),
                ("users_by_role", models.JSONField(default=dict)),
                ("total_queries", models.PositiveIntegerField(default=0)),
                ("queries_24h", models.PositiveIntegerField(default=0)),
                ("avg_response_time", models.FloatField(default=0.0)),
                ("success_rate", models.FloatField(default=100.0)),
                ("queries_by_method", models.JSONField(default=dict)),
                ("failed_logins_24h", models.PositiveIntegerField(default=0)),
                ("locked_accounts", models.PositiveIntegerField(default=0)),
                ("security_events", models.PositiveIntegerField(default=0)),
                ("threat_level", models.CharField(default="low", max_length=10)),
                ("uptime_percentage", models.FloatField(default=100.0)),
                ("avg_cpu_usage", models.FloatField(default=0.0)),
                ("memory_usage_gb", models.FloatField(default=0.0)),
                ("disk_usage_percentage", models.FloatField(default=0.0)),
                ("active_sessions", models.PositiveIntegerField(default=0)),
                ("error_rate", models.FloatField(default=0.0)),
                ("tenant_count", models.PositiveIntegerField(default=0)),
                ("workspace_count", models.PositiveIntegerField(default=0)),
                ("data_processed_gb", models.FloatField(default=0.0)),
                ("export_count_24h", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "analytics_snapshots",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CustomMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "query",
                    models.TextField(
                        help_text="SQL or Elasticsearch query to fetch data"
                    ),
                ),
                (
                    "visualization_type",
                    models.CharField(
                        choices=[
                            ("line", "Line Chart"),
                            ("bar", "Bar Chart"),
                            ("pie", "Pie Chart"),
                            ("number", "Single Number"),
                            ("gauge", "Gauge"),
                            ("table", "Table"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "refresh_interval",
                    models.PositiveIntegerField(
                        default=300, help_text="Refresh interval in seconds"
                    ),
                ),
                ("tenant_id", models.UUIDField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_executed", models.DateTimeField(blank=True, null=True)),
                ("execution_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "analytics_custom_metrics",
            },
        ),
        migrations.CreateModel(
            name="MetricData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField(help_text="Metric result data")),
                (
                    "current_value",
                    models.FloatField(
                        blank=True,
                        help_text="Single numeric value for simple metrics",
                        null=True,
                    ),
                ),
                ("execution_time_ms", models.PositiveIntegerField()),
                ("record_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "analytics_metric_data",
                "ordering": ["-timestamp"],
            },
        ),
    ]
