# Generated by Django 5.1 on 2025-08-23 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="analytics.alertrule",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticssnapshot",
            index=models.Index(
                fields=["timestamp"], name="analytics_s_timesta_ee22af_idx"
            ),
        ),
        migrations.AddField(
            model_name="custommetric",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_metrics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="metricdata",
            name="metric",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_points",
                to="analytics.custommetric",
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["tenant_id", "is_active"], name="analytics_a_tenant__dd997a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["metric_name", "is_active"],
                name="analytics_a_metric__6bdf46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["rule", "status"], name="analytics_a_rule_id_b6e49f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["triggered_at"], name="analytics_a_trigger_cc689d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="custommetric",
            index=models.Index(
                fields=["tenant_id", "is_active"], name="analytics_c_tenant__b260fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="custommetric",
            index=models.Index(
                fields=["created_by", "is_active"],
                name="analytics_c_created_ec19ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="custommetric",
            index=models.Index(
                fields=["is_public", "is_active"], name="analytics_c_is_publ_f16206_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metricdata",
            index=models.Index(
                fields=["metric", "timestamp"], name="analytics_m_metric__73cb8b_idx"
            ),
        ),
    ]
