# Generated by Django 5.1 on 2025-08-22 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QueryTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                ("prompt", models.TextField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("constrained", "Constrained Generation"),
                            ("rules", "Rule-based"),
                            ("zeroshot", "Zero-shot"),
                        ],
                        max_length=20,
                    ),
                ),
                ("index", models.CharField(default="logs_net", max_length=100)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QueryExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                ("total_hits", models.IntegerField()),
                ("returned_hits", models.IntegerField()),
                ("execution_time_ms", models.IntegerField()),
                ("max_size", models.IntegerField(default=1000)),
                ("results", models.JSONField(default=list)),
                ("aggregations", models.JSONField(default=dict)),
                (
                    "export_csv_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "export_json_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="queries.querytask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elasticsearch_dsl", models.JSONField()),
                (
                    "validation_status",
                    models.CharField(
                        choices=[("PASS", "Pass"), ("FAIL", "Fail")], max_length=20
                    ),
                ),
                ("validation_errors", models.JSONField(default=list)),
                ("generation_metrics", models.JSONField(default=dict)),
                ("retry_count", models.IntegerField(default=0)),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_query",
                        to="queries.querytask",
                    ),
                ),
            ],
        ),
    ]
