# Generated by Django 5.1 on 2025-08-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("queries", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="queryexecution",
            options={"ordering": ["-executed_at"]},
        ),
        migrations.AddIndex(
            model_name="generatedquery",
            index=models.Index(
                fields=["validation_status"], name="queries_gen_validat_c16e13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedquery",
            index=models.Index(fields=["task"], name="queries_gen_task_id_e73343_idx"),
        ),
        migrations.AddIndex(
            model_name="queryexecution",
            index=models.Index(
                fields=["task", "-executed_at"], name="queries_que_task_id_9bb921_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="queryexecution",
            index=models.Index(
                fields=["-executed_at"], name="queries_que_execute_a5520d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="queryexecution",
            index=models.Index(
                fields=["total_hits"], name="queries_que_total_h_2f0d7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="queryexecution",
            index=models.Index(
                fields=["execution_time_ms"], name="queries_que_executi_477533_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="querytask",
            index=models.Index(
                fields=["status", "-created_at"], name="queries_que_status_ad6951_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="querytask",
            index=models.Index(
                fields=["method", "-created_at"], name="queries_que_method_7e0615_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="querytask",
            index=models.Index(
                fields=["index", "-created_at"], name="queries_que_index_28a729_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="querytask",
            index=models.Index(
                fields=["-created_at"], name="queries_que_created_c479e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="querytask",
            index=models.Index(
                fields=["task_id"], name="queries_que_task_id_cebd55_idx"
            ),
        ),
    ]
