# Generated by Django 5.1 on 2025-08-22 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdversarialPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_id", models.CharField(max_length=50, unique=True)),
                ("prompt_text", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("injection", "Prompt Injection"),
                            ("bypass", "Security Bypass"),
                            ("extraction", "Data Extraction"),
                            ("manipulation", "Query Manipulation"),
                            ("escalation", "Privilege Escalation"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "expected_behavior",
                    models.TextField(
                        help_text="Expected system behavior (abstain, reject, etc.)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "severity", "prompt_id"],
            },
        ),
        migrations.CreateModel(
            name="SecurityTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_id",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                ("test_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("method", models.CharField(max_length=20)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("total_prompts", models.IntegerField(default=0)),
                ("abstain_count", models.IntegerField(default=0)),
                ("malicious_count", models.IntegerField(default=0)),
                ("valid_count", models.IntegerField(default=0)),
                ("abstain_rate", models.FloatField(blank=True, null=True)),
                ("security_pass_rate", models.FloatField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_id",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                ("generated_query", models.JSONField(blank=True, null=True)),
                ("generation_time", models.FloatField()),
                ("abstained", models.BooleanField(default=False)),
                ("validation_passed", models.BooleanField()),
                ("validation_errors", models.JSONField(default=list)),
                ("is_malicious", models.BooleanField(default=False)),
                (
                    "security_risk_level",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("security_notes", models.TextField(blank=True)),
                ("tested_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="completed", max_length=20)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="security.adversarialprompt",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="security.securitytest",
                    ),
                ),
            ],
            options={
                "ordering": ["-tested_at"],
                "unique_together": {("test", "prompt")},
            },
        ),
    ]
