# Generated by Django 5.1 on 2025-08-23 14:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CICDatasetFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_id", models.CharField(max_length=50, unique=True)),
                ("filename", models.CharField(max_length=200)),
                ("file_path", models.CharField(max_length=1000)),
                ("day_of_week", models.CharField(blank=True, max_length=20)),
                ("time_period", models.CharField(blank=True, max_length=50)),
                ("attack_types", models.JSONField(default=list)),
                ("original_size", models.BigIntegerField(blank=True, null=True)),
                ("record_count", models.IntegerField(blank=True, null=True)),
                ("processed_record_count", models.IntegerField(blank=True, null=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("is_ingested", models.BooleanField(default=False)),
                ("processed_file_path", models.CharField(blank=True, max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["filename"],
            },
        ),
        migrations.CreateModel(
            name="DataIngestionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                ("task_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("source_file", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "dataset_type",
                    models.CharField(
                        choices=[
                            ("cic_ids2017", "CIC-IDS2017 Dataset"),
                            ("general_csv", "General CSV"),
                            ("network_logs", "Network Logs"),
                            ("other", "Other"),
                        ],
                        default="general_csv",
                        max_length=50,
                    ),
                ),
                ("target_index", models.CharField(max_length=100)),
                ("chunk_size", models.IntegerField(default=5000)),
                ("sample_size", models.IntegerField(blank=True, null=True)),
                ("create_index", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_records", models.IntegerField(blank=True, null=True)),
                ("processed_records", models.IntegerField(default=0)),
                ("failed_records", models.IntegerField(default=0)),
                ("progress_percentage", models.FloatField(default=0.0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_time_seconds", models.IntegerField(blank=True, null=True)),
                ("success_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("error_messages", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ElasticsearchIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index_name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("mapping_file", models.CharField(blank=True, max_length=500)),
                (
                    "index_type",
                    models.CharField(
                        choices=[
                            ("logs_net", "Standard Network Logs"),
                            ("logs_cic_ids2017", "CIC-IDS2017 Logs"),
                            ("logs_dp", "Differential Privacy Logs"),
                            ("custom", "Custom Index"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                ("document_count", models.BigIntegerField(default=0)),
                ("index_size_bytes", models.BigIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["index_name"],
            },
        ),
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload_id",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                ("original_filename", models.CharField(max_length=500)),
                ("file_path", models.CharField(max_length=1000)),
                ("file_size", models.BigIntegerField()),
                ("content_type", models.CharField(max_length=100)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("csv", "CSV File"),
                            ("json", "JSON File"),
                            ("jsonl", "JSONL File"),
                            ("pcap", "PCAP File"),
                            ("other", "Other"),
                        ],
                        default="csv",
                        max_length=50,
                    ),
                ),
                ("sample_data", models.JSONField(blank=True, null=True)),
                ("column_names", models.JSONField(default=list)),
                ("estimated_records", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("analyzed", "Analyzed"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
